#!/usr/bin/env python3

# Convert a DBK transaction CSV file to a YNAB account CSV file

import sys
import re
import io
import csv
import datetime

import chardet

# Account CSV header
ACC_HEADER = """
Booking date;
Value date;
Transaction Type;
Beneficiary / Originator;
Payment Details;
IBAN;
BIC;
Customer Reference;
Mandate Reference;
Creditor ID;
Compensation amount;
Original Amount;
Ultimate creditor;
Number of transactions;
Number of cheques;
Debit;
Credit;
Currency
""".replace("\n", "")

# Account CSV offset values
ACC_BOOKING_DATE = 0
ACC_BENEFICIARY = 3
ACC_PAYMENT_DETAILS = 4
ACC_DEBIT = 15
ACC_CREDIT = 16

# Credit card CSV header
CC_HEADER = """
Voucher date;
Date of receipt;
Reason for payment;
Foreign currency;
Amount;
Exchange rate;
Amount;
Currency
""".replace("\n", "")

# Credit card CSV offset values
VOUCHER_DATE = 0
REASON = 2
AMOUNT = 6

def help():
    "Print usage information and exit"
    print("Usage: %s [-a|-c] < FILE" % sys.argv[0])
    sys.exit(1)

def error(msg):
    "Print error and exit"
    print("Error: %s" % msg)
    sys.exit(1)

def fmt_date(date):
    "Switch date format from American to European"
    date = datetime.datetime.strptime(date, "%m/%d/%Y")
    date = date.strftime("%d/%m/%Y")
    return date

def payee(beneficiary, details):
    "Get payee from transaction details"
    # Remove repetition
    details = details.replace(beneficiary, "")
    # Join fields to get some semblance of a payee
    str = " ".join([beneficiary, details])
    # if you want to see less data in details just remove numbers like nslater was doing:
    # return " ".join(s for s in str.split() if not any(c.isdigit() for c in s))
    return str

def unsign(str):
    "Get unsigned number"
    # YNAB doesn't like signed values
    return str.replace("-", "").strip()

def convert_account(row):
    "Convert from Deutsche Bank account format to YNAB format"
    date = fmt_date(row[ACC_BOOKING_DATE])
    desc = payee(row[ACC_BENEFICIARY], row[ACC_PAYMENT_DETAILS])
    debit = unsign(row[ACC_DEBIT])
    credit = row[ACC_CREDIT]
    return [date, desc, "", "", debit, credit]

def convert_cc(row):
    "Convert from Deutsche Bank credit card format to YNAB format"
    date = fmt_date(row[VOUCHER_DATE])
    payee = row[REASON]
    if "-" in row[AMOUNT]:
        debit = unsign(row[AMOUNT])
        credit = ""
    else:
        debit = ""
        credit = unsign(row[AMOUNT])
    return [date, payee, "", "", debit, credit]

# Check that a filename is passed
try:
    in_filename = sys.argv[1]
except:
    help()

# Read stdin in binary mode
in_file_b = open(in_filename, "rb").read()

# Guess encoding
in_file_enc = chardet.detect(in_file_b)

# Attempt decoding
in_file_s = in_file_b.decode(in_file_enc["encoding"])

# Set well-formed flag
well_formed = False

convert = None

# Filter out the garbage
csv_lines = []
for line in in_file_s.split("\n"):
    if line == ACC_HEADER:
        convert = convert_account
        well_formed = True
    if line == CC_HEADER:
        convert = convert_cc
        well_formed = True
    if re.match("^\d+/\d+/\d+;", line):
        csv_lines.append(line)
csv_s = "\n".join(csv_lines)

if not well_formed:
    raise error("CSV file is not well-formed!")

# Parse as a CSV file
reader = csv.reader(io.StringIO(csv_s), delimiter=";")

# Prepare to write to stdout
writer = csv.writer(sys.stdout)

# Write CSV header
writer.writerow(["Date", "Payee", "Category", "Memo", "Outflow", "Inflow"])

# Convert all lines and output
for row in reader:
    writer.writerow(convert(row))
